### ISSUE TITLE
Complied version for MAC CPU?

### ISSUE THREAD

**Issue by ConfusedKoala** [turtlecoin/ninjarig#12]
hi.. is there a complied version for OSX to mine using cpu? Thanks alot.

**Comment by bogdanadnan** [comment]
For short term I don't have in plans to add mac os binary because of lack of easy dependency management. That may change though later on. You might try compiling by yourself, should not be too difficult. I suggest using brew to install dependencies (https://brew.sh/index).

**Comment by IgnacioLPM** [comment]
https://github.com/xmrig/xmrig/wiki/macOS-Build

You need Xcode and Homebrew installed.

brew install cmake libuv libmicrohttpd openssl hwloc
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
make

**Comment by brandonlehmann** [comment]
Unmaintained or Supported.
