### ISSUE TITLE
AMD Radeon 5700 XT shares being rejected by Turtlecoin pools

### ISSUE THREAD

**Issue by cryptocool** [turtlecoin/ninjarig#13]
AMD Radeon 5700 XT with Ninjarig v1.0.3_08.09.2019_windows_10. 19.7.4 Adrenalin drivers are suggested by AMD technical support. All my shares are being rejected on all the Turtlecoin pools. Is this GPU supported ?
Thanks!

**Comment by SoreGums** [comment]
maybe a screenshot of the top part ninjarig spits out?

**Comment by cryptocool** [comment]
Here are the screenshots.

[image: image.png]

[image: image.png]

**Comment by SoreGums** [comment]
do u see images on the website?

https://github.com/turtlecoin/ninjarig/issues/13

i don't think they uploaded

**Comment by cryptocool** [comment]
I am reading on reddit that the 5700 XT is not supported yet. No worries.
![image](https://user-images.githubusercontent.com/6797591/65015349-4a7cff80-d8ef-11e9-9eff-cefcb998cce9.png)
![image(1)](https://user-images.githubusercontent.com/6797591/65015357-51a40d80-d8ef-11e9-865c-60e4c89db806.png)

**Comment by SoreGums** [comment]
indeed amd need to sort there drivers out https://www.anandtech.com/show/14618/the-amd-radeon-rx-5700-xt-rx-5700-review/13

bogdanadnan is working on native amd implementation too - so that might work once released if amd haven't bothered

**Comment by markveon** [comment]
@SoreGums Every works perfect on Radeon VII, but same issue on 5700xt

**Comment by Sajo8** [comment]
Any updates yet?

**Comment by image28** [comment]
Have it working in Arch-linux with the 19.50 drivers, steam isn't now however :(
Get 50-100kH/s with the Saphire RT 5500 XT 8GB card.

**Comment by image28** [comment]
0 Rejected shares, can only run it for 15 minute intervals as I have a possible fan issue and the junction can get to 100°C after 10-15 minutes.

Let me know if any of my system info could help debugging the issue!

**Comment by image28** [comment]
Could it be the difficulty setting is too low for the gpu? Not sure how you choose the difficulty on mine2gether.com

**Comment by brandonlehmann** [comment]
Unmaintained or Supported.
