### ISSUE TITLE
Trouble building for Centos 7

### ISSUE THREAD

**Issue by ibrahimk157** [turtlecoin/ninjarig#19]
Hello,

I recently tried to compile ninjarig for centos. However, due to the lack of build instructions for centos specifically, I faced some trouble.

First things first, the package names for centos are different from those you advised to install in the ubuntu instructions. So I just assumed that I had them since I’ve compiled xmrig before with zero issues.

However, seems like I am missing something or I’ve done something wrong. When i try to run “make” to start the build process, I kept on getting a few errors in between and a huge error at the end.

Here’s the output from the second i ran “make” to the point where it failed and returned me to the console. https://pastebin.com/494Miu5x

I am highly inexperienced in this stuff, so apologies if the error is too obvious. I simply am not able to figure out what’s wrong.

Thank you.

**Comment by ibrahimk157** [comment]
Anyone?

**Comment by brandonlehmann** [comment]
Let's see the output of your cmake

**Comment by ibrahimk157** [comment]
> Let's see the output of your cmake

Here you go https://pastebin.com/UU5GvB5h

**Comment by brandonlehmann** [comment]
That version of GCC (4.x.x) is ancient and still believes the world is flat.

Try using a newer version of GCC

```bash
sudo yum update -y
sudo yum install -y epel-release centos-release-scl
sudo yum install -y devtoolset-8
scl enable devtoolset-8 bash
cmake -DWITH_CUDA=OFF -DWITH_OPENCL=OFF .. -DCMAKE_BUILD_TYPE=RELEASE
```

These two lines should then show a 8.x.x GCC version:

```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
```

**Comment by ibrahimk157** [comment]
> That version of GCC (4.x.x) is ancient and still believes the world is flat.
> 
> Try using a newer version of GCC
> 
> ```shell
> sudo yum update -y
> sudo yum install -y epel-release centos-release-scl
> sudo yum install -y devtoolset-8
> scl enable devtoolset-8 bash
> cmake -DWITH_CUDA=OFF -DWITH_OPENCL=OFF .. -DCMAKE_BUILD_TYPE=RELEASE
> ```
> 
> These two lines should then show a 8.x.x GCC version:
> 
> ```
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> ```

Worked like a charm! Thanks a lot!
