### ISSUE TITLE
 request for add Ninja variant (please)

### ISSUE THREAD

**Issue by NinjaCoin-Master** [turtlecoin/ninjarig#23]
hi, can you please add the ninja variant?

// Ninja Definitions
#define NINJA_HASHLEN 32 // The length of the resulting hash in bytes
#define NINJA_SALTLEN 16 // The length of our salt in bytes
#define NINJA_THREADS 1 // How many threads to use at once
#define NINJA_ITERS 4 // How many iterations we perform as part of our slow-hash
#define NINJA_MEMORY 128 // This value is in KiB (0.1MB)

**Comment by 0des** [comment]
This is out of scope for TurtleCoin. You must fork the repository and complete the modification on your own. 
![image](https://user-images.githubusercontent.com/52985253/80500699-1e6d3680-8934-11ea-9d95-ebc064b3f131.png)
