### ISSUE TITLE
No hashrate on Termux 

### ISSUE THREAD

**Issue by nakanakaii** [turtlecoin/ninjarig#24]
I've followed the instructions in this [Tutorial](https://docs.turtlecoin.lol/guides/mining/using-termux) Carefully

But after running the command 
> ./ninjarig-notls

 It just give my n/a H/s several times then showing the alert 

> [2020-05-04 07:59:55] [stratum+tcp://stratum.slushpool.com:3333] read error: "end of file"

Termux Version 0.94

**Comment by brandonlehmann** [comment]
Unmaintained or Supported.
