### ISSUE TITLE
Dev mining not working propperly

### ISSUE THREAD

**Issue by Nikovash** [turtlecoin/ninjarig#25]
During the development mining cycle it connects to the pool, but hashes at 0%. I am not sure if this is just a current problem with the current dev pool that you are mining to or what, but I want this project to stay alive and understand the importance of dev mining.

**Comment by 0des** [comment]
We do not support fork projects.

**Comment by Nikovash** [comment]
so ninjarig doesn't dev mine for itself?.... .... isnt this the github for ninjarig?

**Comment by brandonlehmann** [comment]
> so ninjarig doesn't dev mine for itself?.... .... isnt this the github for ninjarig?

This project is a fork or xmrig. The developer miner settings remain unchanged from xmrig. xmrig doesn’t have target dev pools for every project supported.

**Comment by brandonlehmann** [comment]
Unmaintained or Supported.
