### ISSUE TITLE
installing Error

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [turtlecoin/ninjarig#26]
Hello I'm trying something new. I'm new to linux somwhat not a programmer at all. I'm trying to install the Gpu version of ninjarig for turtlecoin So i went to mine2gether welcome said to install the # For CPU, OpenCL, and CUDA and go to ninjarig and grab that. So i followed everything into i got to $ cmake .. -DCMAKE_BUILD_TYPE=RELEASE $  and when i got to make i get this eror.

-- Configuring incomplete, errors occurred!
See also "/home/masternode/miner/ninjarig/build/CMakeFiles/CMakeOutput.log".
See also "/home/masternode/miner/ninjarig/build/CMakeFiles/CMakeError.log".
masternode@masternode:~/miner/ninjarig/build$ make
make: *** No targets specified and no makefile found.  Stop.

Not sure what to do can someone please help me?

Joseph

**Comment by zpalmtree** [comment]
Your make is failing because your cmake is failing. Post the cmake output.

**Comment by Therealjosephchrzempiec** [comment]
Oh I'm sorry here it is. 

`-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture is: x86_64
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenCL.cmake:132 (find_package_handle_standard_args)
  CMakeLists.txt:377 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/masternode/miner/ninjarig/build/CMakeFiles/CMakeOutput.log".
See also "/home/masternode/miner/ninjarig/build/CMakeFiles/CMakeError.log".
masternode@masternode:~/miner/ninjarig/build$ make
make: *** No targets specified and no makefile found.  Stop.
`
It looks like it  opencl problem not there. Im not sure what the opencl is for?

oseph

**Comment by zpalmtree** [comment]
OpenCL is one of the two libraries you can use to run GPU code. What GPU do you have? If you have a nvidia one, you can disable this, because it will use CUDA instead. If you have an AMD GPU, you will need to acquire openCL to mine with your GPU.

**Comment by zpalmtree** [comment]
You can give the `-DWITH_OPENCL=OFF` flag to cmake to disable compiling with OPENCL support.

e.g. `cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_OPENCL=OFF`

**Comment by Therealjosephchrzempiec** [comment]
Hello thank you i will try this,

**Comment by Therealjosephchrzempiec** [comment]
Hello That command worked thank you, this is the command i found online. I'm not sure what i do for this part <OPENCL,CUDA> --gpu-filter <filters like: OPENCL:AMD,CUDA:1070>and <intensity from 1-100> 

ninjarig -a chukwa -o stratum+tcp://myturtleaddress -u mywallet -p masternode -t 0 --use-gpu <OPENCL,CUDA> --gpu-filter <filters like: OPENCL:AMD,CUDA:1070> --gpu-intensity <intensity from 1-100>

**Comment by Therealjosephchrzempiec** [comment]
I see the intensity i for the gpu memory. and gpu filter is for unsure of so i did this.

 ninjarig -a chukwa -o stratum+tcp://myturtleaddress -u mywallet -p masternode -t 0 --use-gpu CUDA --gpu-filter CUDA:1070 --gpu-intensity <intensity from 1-100>
And this is what i got as a new error. -bash: syntax error near unexpected token `newline' 

I do fill in the address for the miner and mywallet address i just post it in here.

**Comment by zpalmtree** [comment]
Try using a config file instead of using startup params: https://docs.turtlecoin.lol/guides/mining/ninjarig-guide

I think it should also use your GPU by default without specifying the filter/use gpu etc flags.

**Comment by Therealjosephchrzempiec** [comment]
Hello that page doesn't explain how to setup a config file like other sites. It just say to put pool address and wallet address nothing else. There is no config example on the page.

**Comment by zpalmtree** [comment]
You can get an example config file from the precompiled binaries download: https://github.com/turtlecoin/ninjarig/releases/tag/v1.0.3

**Comment by Therealjosephchrzempiec** [comment]
Hello sorry i can not download anything bececause I'm on the road and i have a slow internet connection. It will take forever to download. I can putty into my system but that is all and barely get online here.

**Comment by zpalmtree** [comment]
Here is the contents. This looks like its setup for an AMD gpu, but if it doesn't work you can remove the `use-gpu` and `gpu-filter` keys and it should find your nvidia GPU anyway.
```json
{
    "algo": "chukwa",
    "api": {
        "port": 10000,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "cpu-threads": 2,
    "cpu-optimization": null,
    "cpu-affinity": null,
    "priority": null,
    "donate-level": 5,
    "log-file": null,
    "pools": [
        {
            "url": "stratum+tcp://trtl.muxdux.com:5555",
            "user": "TRTLuxUdNNphJcrVfH27HMZumtFuJrmHG8B5ky3tzuAcZk7UcEdis2dAQbaQ2aVVGnGEqPtvDhMgWjZdfq8HenxKPEkrR43K618",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": "chukwa",
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "user-agent": null,
    "syslog": false,
    "watch": true,
    "use-gpu": [
        "OPENCL",
        "CUDA"
    ],
    "gpu-intensity": [
        50.0
    ],
    "gpu-filter": [
        {
            "engine": "OPENCL",
            "filter": "AMD"
        },
        {
            "engine": "OPENCL",
            "filter": "Radeon"
        },
        {
            "engine": "OPENCL",
            "filter": "Advanced Micro Devices"
        }
    ]
}
```

**Comment by Therealjosephchrzempiec** [comment]
Hello Thank you very much you are a lifesaver. I'm mking a config file now. Do i put it in the mainninjarig directory or in the build directory?  I'm sorry for al these problems.  Still new and trying to figure this all out. Also i never started a config before what is the command for this please?

**Comment by zpalmtree** [comment]
I believe it will automatically read a `config.json` in the same directory as the binary. You can also use the `--config` arg to specify a specific path, e.g. `./ninjarig --config /home/foo/config.json`

**Comment by Therealjosephchrzempiec** [comment]
Hello config file made and all information input. But not sure how to start it in terminal this way?

**Comment by zpalmtree** [comment]
Did you see the previous comment?



> I believe it will automatically read a `config.json` in the same directory as the binary. You can also use the `--config` arg to specify a specific path, e.g. `./ninjarig --config /home/foo/config.json`

I don't believe there are any required arguments other than a config file. Just run that command right in your terminal in the ninjarig binary directory.

**Comment by Therealjosephchrzempiec** [comment]
It has been a long time sense i ran a command to start something.  This is my first time in many years. Not even sure what is the command to start it. And back then i wasn't that good either at doing things in command line.

**Comment by Therealjosephchrzempiec** [comment]
Hello just a update Not sure what I'm doing wrong but i have tired ./ninjarig to start it and i get a eror saying ./ninjarig: No such file or directory. i was in the main ninjarig folder. have also tried it in the build folder and i get the same eror.

I wasn't sure if that was me i did something wrong or what was the problem?

**Comment by zpalmtree** [comment]
binary should be somewhere in the build folder, yep

do `ls` to see files in the directory.
did you re-run `make` after getting the `cmake` to complete?

**Comment by Therealjosephchrzempiec** [comment]
hello no i did rerun any make or cmake after i made the config file. So do i need to redo the cmake and then the make again?

**Comment by zpalmtree** [comment]
Not after changing the config file, but previously your make error'd out, i'm not sure if you ever let it complete after fixing the cmake to finish the build process

**Comment by Therealjosephchrzempiec** [comment]
ohh hmm not sure  i didn't see no erorr after that one command for cmake you gave me. Let me do this. I have time somewhat. I can make a new directory and try this again and see what hppens. Because I'm not sure what is going on and why i can not run this. But if i try again atleast i can see if there is any errors. I will update this post shortly and thank you for all the help. Sorry for being a pain.

**Comment by Therealjosephchrzempiec** [comment]
Some odd reason when i go into the releases i get  page can not be displayed. But if i go into the main github site I'm okay. If i go into my account I'm okay. I'm not sure what is going on.

**Comment by Therealjosephchrzempiec** [comment]
I will have to pick this back up in the morning my time it is 2:14am here. Have a good one and thank you for the help i will post a update later on.

**Comment by Therealjosephchrzempiec** [comment]
Hello Zpalmtree I'm back at it once gain to try this. So these are the commands i use to get do everything and what errors i got so far.

i did a 
wget https://github.com/turtlecoin/ninjarig/releases/download/v1.0.3/ninjarig_v1.0.3_08.09.2019_linux.tar.gz
unzip: sudo tar xzvf ninjarig_v1.0.3_08.09.2019_linux.tar.gz
cd into folder ninjarig_v1.0.3_08.09.2019_linux
then i mkdir a build folder 
cd into folder Build
then did a cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_OPENCL=OFF
and i got this message.
CMake Error: The source directory "/home/masternode/miner/ninjarig_v1.0.3_08.09.2019_linux" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

So i looked and no it doesn't contain that file.


Joseph

**Comment by zpalmtree** [comment]
You have downloaded the binaries, which has the already compiled linux miner in, it doesn't have the source code to compile. You need to clone/download a zip of the repo if you want to compile it.

**Comment by Therealjosephchrzempiec** [comment]
okay so basically I'm messing it up. What should i do to get downlaoded and install what steps should i take. I'm going a little nuts. So I'm making it worse.

**Comment by zpalmtree** [comment]
Depending on the distribution you're using, you should be able to use the downloaded binaries and run them straight away. 

When you are in the `ninjarig_v1.0.3_08.09.2019_linux` folder, you should be able to run `./ninjarig`. If that doesn't work then do `ls` and look at the files, maybe it is named something slightly different. If you see errors about missing libraries when you run it, then you'll need to compile yourself. You can fetch that code by running `git clone https://github.com/turtlecoin/ninjarig.git`

**Comment by Therealjosephchrzempiec** [comment]
The one on the main page says its a ver of 1.0 and not the 1.0.3.  Would it still be okay to git the https://github.com/turtlecoin/ninjarig.git ?

**Comment by zpalmtree** [comment]
The git repository hosts the latest code. The readme has just not been updated.

**Comment by Therealjosephchrzempiec** [comment]
Okay let me try this. I went to https://github.com/turtlecoin/ninjarig and followed the linux one.
sudo apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev gcc-8 g++-8
export CC=gcc-8
export CXX=g++-8
git clone https://github.com/turtlecoin/ninjarig.git && cd ninjarig
mkdir build && cd build
Then i added what you said to do. 
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_OPENCL=OFF
make

Is there anything else I'm missing for the install?

**Comment by zpalmtree** [comment]
Looks ok

**Comment by Therealjosephchrzempiec** [comment]
Okay i got my first error. When i typed in make after the cmake one i get this error.

CMakeFiles/cuda_hasher.dir/build.make:63: recipe for target 'CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/cuda_hasher_generated_cuda_kernel.cu.o' failed
make[2]: *** [CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/cuda_hasher_generated_cuda_kernel.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_hasher.dir/all' failed
make[1]: *** [CMakeFiles/cuda_hasher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zpalmtree** [comment]
There should be output somewhere from the `make` command that indicates what caused compilation of that file to fail. Just post the full command output if you don't know which bit it is.

**Comment by zpalmtree** [comment]
If you're having issues compiling, trying out the precompiled binaries might be an idea. Or, give violetminer a try https://docs.turtlecoin.lol/guides/mining/violetminer-guide

**Comment by Therealjosephchrzempiec** [comment]
Let's see if i can do this and post it without taking a lot of room here. 

```
masternode@masternode:~/miner3/ninjarig/build$ make
Scanning dependencies of target argon2_common
[  0%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/common/common.cpp.o
[  1%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/crypt/base64.cpp.o
[  2%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/crypt/hex.cpp.o
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/crypt/hex.cpp: In static member function ‘static int hex::decode(const char*, unsigned char*, int)’:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/crypt/hex.cpp:24:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for ( int i=0; i<in_len; i+=2 ) {
                    ~^~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
[  3%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/crypt/random_generator.cpp.o
[  4%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/crypt/sha512.cpp.o
[  5%] Building C object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/hash/argon2/blake2/blake2b.c.o
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/blake2/blake2b.c:54:27: warning: ‘blake2b_sigma’ defined but not used [-Wunused-const-variable=]
 static const unsigned int blake2b_sigma[12][16] = {
                           ^~~~~~~~~~~~~
[  6%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/hash/argon2/Argon2.cpp.o
In file included from /home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/Argon2.cpp:12:0:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h: In function ‘int xmrig::argon2_select_algo(xmrig::Variant)’:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:34:16: warning: enumeration value ‘VARIANT_AUTO’ not handled in switch [-Wswitch]
         switch (variant)
                ^
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:34:16: warning: enumeration value ‘VARIANT_MAX’ not handled in switch [-Wswitch]
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h: In function ‘uint64_t xmrig::argon2_select_memory(xmrig::Variant)’:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:47:16: warning: enumeration value ‘VARIANT_AUTO’ not handled in switch [-Wswitch]
         switch (variant)
                ^
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:47:16: warning: enumeration value ‘VARIANT_MAX’ not handled in switch [-Wswitch]
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h: In function ‘uint32_t xmrig::argon2_select_iters(xmrig::Variant)’:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:60:16: warning: enumeration value ‘VARIANT_AUTO’ not handled in switch [-Wswitch]
         switch (variant)
                ^
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:60:16: warning: enumeration value ‘VARIANT_MAX’ not handled in switch [-Wswitch]
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h: In function ‘uint32_t xmrig::argon2_select_parallelism(xmrig::Variant)’:
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:73:16: warning: enumeration value ‘VARIANT_AUTO’ not handled in switch [-Wswitch]
         switch (variant)
                ^
/home/masternode/miner3/ninjarig/src/crypto/argon2_hasher/hash/argon2/../../../Argon2_constants.h:73:16: warning: enumeration value ‘VARIANT_MAX’ not handled in switch [-Wswitch]
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
[  7%] Building C object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/hash/argon2/argon2profile_4_1_256.c.o
[  8%] Building C object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/hash/argon2/argon2profile_3_1_512.c.o
[  9%] Building CXX object CMakeFiles/argon2_common.dir/src/crypto/argon2_hasher/hash/Hasher.cpp.o
[ 10%] Building CXX object CMakeFiles/argon2_common.dir/src/core/HasherConfig.cpp.o
/home/masternode/miner3/ninjarig/src/core/HasherConfig.cpp: In member function ‘double xmrig::HasherConfig::getGPUIntensity(int)’:
/home/masternode/miner3/ninjarig/src/core/HasherConfig.cpp:72:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(cardIndex < m_gpuIntensity.size())
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/masternode/miner3/ninjarig/src/core/HasherConfig.cpp: In member function ‘int64_t xmrig::HasherConfig::getCPUAffinity(int)’:
/home/masternode/miner3/ninjarig/src/core/HasherConfig.cpp:91:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (idx == cpuIndex) {
                 ~~~~^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
[ 11%] Linking CXX shared library libargon2_common.so
[ 11%] Built target argon2_common
[ 12%] Building NVCC (Device) object CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/cuda_hasher_generated_cuda_kernel.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at cuda_hasher_generated_cuda_kernel.cu.o.RELEASE.cmake:221 (message):
  Error generating
  /home/masternode/miner3/ninjarig/build/CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/./cuda_hasher_generated_cuda_kernel.cu.o


CMakeFiles/cuda_hasher.dir/build.make:63: recipe for target 'CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/cuda_hasher_generated_cuda_kernel.cu.o' failed
make[2]: *** [CMakeFiles/cuda_hasher.dir/src/crypto/argon2_hasher/hash/gpu/cuda/cuda_hasher_generated_cuda_kernel.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_hasher.dir/all' failed
make[1]: *** [CMakeFiles/cuda_hasher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by zpalmtree** [comment]
Ok, the error is from this bit: `nvcc fatal   : Unsupported gpu architecture 'compute_30'`. I'm not sure the exact cause of this error, but I think it may be because your version of CUDA is too old/new, and doesn't support your GPU.

**Comment by Therealjosephchrzempiec** [comment]
how do i findout what cuda I'm running and what cuda does ninjarig uses?

**Comment by zpalmtree** [comment]
cmake might output the version of cuda it detected. The readme says this:

> CUDA developer toolkit 9 or higher. Provided binaries are compiled with CUDA 10.1. Follow instructions from NVidia site to get the latest version up and running: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html (be careful that CUDA might have specific requirements for compiler version as well)

**Comment by Therealjosephchrzempiec** [comment]
Hello just a update. It looks like the Cuda was not good because it was the latest 11 and i searched online to downgrade to 10.1 that seem to work i did a make and now no errors.

But when i ran  this command ninjarig -a chukwa -o stratum+tcp://trtl.pool.mine2gether.com:3335 -u mywallet -p masternode -t 0 --use-gpu CUDA --gpu-filter CUDA:1080 --gpu-intensity 50 i get the same error. ninjarig: command not found

**Comment by Therealjosephchrzempiec** [comment]
Hello latest update. It works now. I made a config file  i added it into the main ninjarig folder try to run it and got the same error. So i moved it into the build folder and ran it now. I do have GPU mining. Thank you so much for the help.
The Cuda was the problem the whole time. Again thank you so much.


Joseph

**Comment by zpalmtree** [comment]
No problem, glad you got it working. Stop by our discord if you want to chat more - http://chat.turtlecoin.lol/

**Comment by Therealjosephchrzempiec** [comment]
I will do that. I just have one last question. For the GPU fan sense I'm running it this way. Wha can i do to make it not overheat and have it automatically cool it's self if need to?

**Comment by zpalmtree** [comment]
Most GPUs will by default spin up their fans as the temperature raises. You can configure these fan curves, I believe nvidia has a utility on linux you can run to do this.

**Comment by Therealjosephchrzempiec** [comment]
But sense I'm only ssh into the system i don't know how to do that.

**Comment by zpalmtree** [comment]
Maybe https://developer.nvidia.com/nvidia-system-management-interface
Start by just monitoring the temperatures, maybe the default is fine.

**Comment by brandonlehmann** [comment]
Y’all should switch to discord. The notifications on this thread are nuts.
