### ISSUE TITLE
Can you add ability to do GPU-solo-mining coins with custom prefix on the daemon?

### ISSUE THREAD

**Issue by username1565** [turtlecoin/ninjarig#28]
Can you add ability to do GPU-solo-mining coins with custom prefix on the daemon?
Like that CPU-miners `miner.exe`? This do solo-mining on the daemon, but using only CPU-threads,
and no any custom prefixes, because prefixes is hardcoded for each coin.
For me, just Interested a `Argon2id/chukwa`-algo, but maybe this can be extended for the more different algos,
to be more universal, and complete.

**Comment by brandonlehmann** [comment]
You’re asking for fork support, right?

**Comment by username1565** [comment]
I do not ask for supporting the some specified fork. Inside blockchain, there can be a many blockchain-forks.

So look at this...
Many turtlecoin-based coins, with mining-algo `Argon2id/chukwa`,
and `cryptonight-based`-algorithms, all this have the default miner, which using CPU-threads.
Something, like `miner.exe`. This is for a specified mining algo, and the coin-prefixes are hardcoded there.
So, IMHO, will be better to create an universal GPU-miner, not a CPU-miner, and create it for all those algo,
and add supporting for specify the custom coin-prefix.

That's all.

**Comment by brandonlehmann** [comment]
Pull requests are welcome. Ask us to maintain code for forks, isn’t.

**Comment by RocksteadyTC** [comment]
I will do this for 500,000,000 TRTL

**Comment by brandonlehmann** [comment]
> I will do this for 500,000,000 TRTL

I will do this for 499,999,999 TRTL
