### ISSUE TITLE
NinjaRig v1.0.0 fails to run on multiple GPUs

### ISSUE THREAD

**Issue by RainbowMiner** [turtlecoin/ninjarig#3]
![image](https://user-images.githubusercontent.com/39437538/64062581-75294180-cbe8-11e9-8ef2-7357e49b5cfe.png)

The miner just ends, after the last line.

If I start the miner on one GPU, only, it runs fine.

**Comment by RainbowMiner** [comment]
More information:
- Windows 10
- No overclocking

**Comment by bogdanadnan** [comment]
This should be fixed with latest version (https://github.com/turtlecoin/ninjarig/releases/tag/v1.0.1), please test and let me know if it works fine now.
