### ISSUE TITLE
ARGON 2 algo how to mine new algos for  turtlecoin algo argon 2

### ISSUE THREAD

**Issue by thanksmia** [turtlecoin/ninjarig#30]
Hi, the miner has set chuwaka algo as main algo  but the  turtlecoin algo is chuwaka 2 when changed crashes,  instructions unclear chuwaka dead, how to mine on new algo chuwaka 2

**Comment by drunkfromcoffee** [comment]
use violetminer/teamredminer/xmrig

**Comment by brandonlehmann** [comment]
This miner is not maintained or supported at this time.
