### ISSUE TITLE
cuda mining shares rejected

### ISSUE THREAD

**Issue by nopoz** [turtlecoin/ninjarig#8]
Shares are rejected with v1.0.1 using my NVIDIA card. Disabled GPU portion of the config and the issue goes away. Tried different pools and get the same results. 

card: RTX 2080 super
nvidia driver: 436.15 DCH (latest as of posting)

```
c:\ninjarig>ninjarig.exe
 * ABOUT        NinjaRig/1.0.1 clang/7.0.1
 * LIBS         libuv/1.9.1 OpenSSL/1.0.2o microhttpd/0.9.55
 * POOL #1      stratum+tcp://turtlecoin.herominers.com:10381 variant chukwa
 * DONATE       1% (change with --donate-level option)
 * COMMANDS     hashrate, pause, resume
 * Initializing CPU hasher:
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Optimization features: SSE2 SSSE3 AVX
Selecting AVX as candidate for hashing algorithm.
Parallelism: 6 concurent threads supported.
Memory: there is enough memory for 6 concurent threads.
Overiding detected optimization feature with AVX2.
Status: ENABLED - with 6 threads.
 * Initializing CUDA hasher:
[1] GeForce RTX 2080 SUPER (8GB)
Status: ENABLED - with 6698 threads.
 * Hashers initialization complete *
[2019-09-04 02:01:35] configuration saved to: "c:\ninjarig\config.json"
[2019-09-04 02:01:35] use pool turtlecoin.herominers.com:10381  78.46.106.203
[2019-09-04 02:01:35] new job from turtlecoin.herominers.com:10381 diff 250012 algo trtl-chukwa
[2019-09-04 02:01:37] rejected (0/1) diff 250012 "Rejected share: invalid result" (156 ms)
[2019-09-04 02:01:42] rejected (0/2) diff 250012 "Rejected share: invalid result" (154 ms)
[2019-09-04 02:01:44] accepted (1/2) diff 250012 (158 ms)
[2019-09-04 02:01:44] rejected (1/3) diff 250012 "Rejected share: invalid result" (257 ms)
[2019-09-04 02:01:45] rejected (1/4) diff 250012 "Rejected share: invalid result" (153 ms)
[2019-09-04 02:01:46] rejected (1/5) diff 250012 "Rejected share: invalid result" (153 ms)
[2019-09-04 02:01:48] Ctrl+C received, exiting
```

Config:

```
{
    "algo": "chukwa",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "cpu-threads": 0,
    "cpu-optimization": "AVX2",
    "cpu-affinity": null,
    "priority": null,
    "donate-level": 1,
    "log-file": null,
    "pools": [
        {
            "url": "stratum+tcp://trtl.pool.mine2gether.com:3335",
            "user": "XXX",
            "pass": "XXX",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": "chukwa",
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "user-agent": null,
    "watch": true,
    "use-gpu": [
        "CUDA"
    ],
    "gpu-intensity": [
        50.0
    ],
    "gpu-filter": []
}
```

**Comment by wll1rah** [comment]
Can you tell me what driver version your using?
Also, if you compiled the software yourself, let me know as well.
Thanks in advance

**Comment by nopoz** [comment]
Windows 10. I didn't compile it, just using the pre-compiled release from here.

**Comment by nopoz** [comment]
Could this be related to the different Cuda versions? I noticed that CryptoDredge has different builds for different Cuda versions. If I use the 0.21.0 cuda 10.1 CryptoDredge version ([CryptoDredge_0.21.0_cuda_10.1_windows.zip](https://github.com/technobyl/CryptoDredge/releases/download/v0.21.0/CryptoDredge_0.21.0_cuda_10.1_windows.zip)), I don't have any issues.

**Comment by nopoz** [comment]
Also, I can't find a driver download link for anything less than 431.60

**Comment by wll1rah** [comment]
https://www.geforce.com/drivers
they are at the bottom, when you scroll down further for windows 10 x64

**Comment by sp33dy** [comment]
To report I have the same issue with my RTX 2080 and I was already on 430. Running with my i9 and RTX (which is doing a lot of work) I see all these rejections and my CPU only rate (in XMRIG) of 40Kh drops to just 1kH with both operating.

**Comment by SoreGums** [comment]
all crypto miners are flagged as bad cause bad guys use them...

there is no way around that when downloading pre-compiled binaries.  

One way around it is to clone source git repo and compile.

_of course, cloning and compiling won't prevent turning your box into a zombie if the code is in fact malicious..._

**Comment by sp33dy** [comment]
Thanks SoreGums. Fix was to downgrade to 430 and to switch to OPENCL.

**Comment by SoreGums** [comment]
any chance you had a go at OPENCL before downgrading drivers?

**Comment by sp33dy** [comment]
No, I didn't, but I've just upgraded to 436.15 to test it. Is definitely running. However, under 430 for the past 6hrs, I averaged ~100kH, but this looks to have dropped to around ~50kH.

**Comment by bogdanadnan** [comment]
This should be fixed with latest release (https://github.com/turtlecoin/ninjarig/releases/tag/v1.0.2). Please test again.

**Comment by sp33dy** [comment]
Can confirm it works beautifully, thank you!
