### ISSUE TITLE
autosave overrides CPU optimisation

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/ninjarig#9]
you already know about this one.

just in case others stumble here and notice.

when setting the CPU optimization in the config.json also change `autosave` to false so it sticks.

My CPU can do AVX2, was only doing AVX until I disabled autosave

**Comment by bogdanadnan** [comment]
This should be fixed with latest release (https://github.com/turtlecoin/ninjarig/releases/tag/v1.0.2). Please test again.

**Comment by SoreGums** [comment]
fixed 👍
